INHERIT: base.yml
plugins:
- search
- glightbox
- blog:
    blog_dir: blog
    post_url_date_format: yyyy-MM-dd
    post_url_format: '{date}-{slug}'
- redirects:
    redirect_maps:
      docs.html.md: docs/index.md
      fly.html.md: docs/fly.md
      fly.md: docs/fly.md
      config-basics.html.md: docs/config-basics.md
      config-basics.md: docs/config-basics.md
      vars.html.md: docs/vars.md
      vars.md: docs/vars.md
      jobs.html.md: docs/jobs.md
      jobs.md: docs/jobs.md
      tasks.html.md: docs/tasks.md
      tasks.md: docs/tasks.md
      builds.html.md: docs/builds.md
      builds.md: docs/builds.md
      observation.html.md: docs/observation.md
      observation.md: docs/observation.md
      getting-started.html.md: docs/getting-started/index.md
      getting-started.md: docs/getting-started/index.md
      quick-start.html.md: docs/getting-started/quick-start.md
      quick-start.md: docs/getting-started/quick-start.md
      tutorial-hello-world.html.md: docs/getting-started/hello-world.md
      tutorial-hello-world.md: docs/getting-started/hello-world.md
      tutorial-inputs-outputs.html.md: docs/getting-started/inputs-outputs.md
      tutorial-inputs-outputs.md: docs/getting-started/inputs-outputs.md
      tutorials-resources.html.md: docs/getting-started/resources.md
      tutorials-resources.md: docs/getting-started/resources.md
      install.html.md: docs/install/index.md
      install.md: docs/install/index.md
      postgresql-node.html.md: docs/install/running-postgres.md
      postgresql-node.md: docs/install/running-postgres.md
      concourse-cli.html.md: docs/install/concourse-cli.md
      concourse-cli.md: docs/install/concourse-cli.md
      concourse-generate-key.html.md: docs/install/generating-keys.md
      concourse-generate-key.md: docs/install/generating-keys.md
      concourse-web.html.md: docs/install/running-web.md
      concourse-web.md: docs/install/running-web.md
      concourse-worker.html.md: docs/install/running-worker.md
      concourse-worker.md: docs/install/running-worker.md
      upgrading-concourse.html.md: docs/install/upgrading-concourse.md
      upgrading-concourse.md: docs/install/upgrading-concourse.md
      auth.html.md: docs/auth-and-teams/index.md
      auth.md: docs/auth-and-teams/index.md
      main-team.html.md: docs/auth-and-teams/main-team.md
      main-team.md: docs/auth-and-teams/main-team.md
      configuring-auth.html.md: docs/auth-and-teams/configuring/index.md
      configuring-auth.md: docs/auth-and-teams/configuring/index.md
      local-auth.html.md: docs/auth-and-teams/configuring/local-user.md
      local-auth.md: docs/auth-and-teams/configuring/local-user.md
      github-auth.html.md: docs/auth-and-teams/configuring/github.md
      github-auth.md: docs/auth-and-teams/configuring/github.md
      gitlab-auth.html.md: docs/auth-and-teams/configuring/gitlab.md
      gitlab-auth.md: docs/auth-and-teams/configuring/gitlab.md
      bitbucket-cloud-auth.html.md: docs/auth-and-teams/configuring/bitbucket-cloud.md
      bitbucket-cloud-auth.md: docs/auth-and-teams/configuring/bitbucket-cloud.md
      cf-uaa-auth.html.md: docs/auth-and-teams/configuring/cf-uaa.md
      cf-uaa-auth.md: docs/auth-and-teams/configuring/cf-uaa.md
      ldap-auth.html.md: docs/auth-and-teams/configuring/ldap.md
      ldap-auth.md: docs/auth-and-teams/configuring/ldap.md
      microsoft-auth.html.md: docs/auth-and-teams/configuring/microsoft.md
      microsoft-auth.md: docs/auth-and-teams/configuring/microsoft.md
      generic-oidc-auth.html.md: docs/auth-and-teams/configuring/generic-oidc.md
      generic-oidc-auth.md: docs/auth-and-teams/configuring/generic-oidc.md
      generic-oauth.html.md: docs/auth-and-teams/configuring/generic-oauth.md
      generic-oauth.md: docs/auth-and-teams/configuring/generic-oauth.md
      generic-saml-auth.html.md: docs/auth-and-teams/configuring/generic-saml.md
      generic-saml-auth.md: docs/auth-and-teams/configuring/generic-saml.md
      managing-teams.html.md: docs/auth-and-teams/managing-teams.md
      managing-teams.md: docs/auth-and-teams/managing-teams.md
      user-roles.html.md: docs/auth-and-teams/user-roles.md
      user-roles.md: docs/auth-and-teams/user-roles.md
      exposing.html.md: docs/auth-and-teams/exposing.md
      exposing.md: docs/auth-and-teams/exposing.md
      teams-caveats.html.md: docs/auth-and-teams/caveats.md
      teams-caveats.md: docs/auth-and-teams/caveats.md
      pipelines.html.md: docs/pipelines/index.md
      pipelines.md: docs/pipelines/index.md
      setting-pipelines.html.md: docs/pipelines/setting-pipelines.md
      setting-pipelines.md: docs/pipelines/setting-pipelines.md
      managing-pipelines.html.md: docs/pipelines/managing-pipelines.md
      managing-pipelines.md: docs/pipelines/managing-pipelines.md
      instanced-pipelines.html.md: docs/pipelines/grouping-pipelines.md
      instanced-pipelines.md: docs/pipelines/grouping-pipelines.md
      resources.html.md: docs/resources/index.md
      resources.md: docs/resources/index.md
      resource-versions.html.md: docs/resources/resource-versions.md
      resource-versions.md: docs/resources/resource-versions.md
      managing-resources.html.md: docs/resources/managing-resources.md
      managing-resources.md: docs/resources/managing-resources.md
      resource-types.html.md: docs/resource-types/index.md
      resource-types.md: docs/resource-types/index.md
      implementing-resource-types.html.md: docs/resource-types/implementing.md
      implementing-resource-types.md: docs/resource-types/implementing.md
      managing-resource-types.html.md: docs/resource-types/managing-types.md
      managing-resource-types.md: docs/resource-types/managing-types.md
      steps.html.md: docs/steps/index.md
      steps.md: docs/steps/index.md
      get-step.html.md: docs/steps/get.md
      get-step.md: docs/steps/get.md
      put-step.html.md: docs/steps/put.md
      put-step.md: docs/steps/put.md
      task-step.html.md: docs/steps/task.md
      task-step.md: docs/steps/task.md
      set-pipeline-step.html.md: docs/steps/set-pipeline.md
      set-pipeline-step.md: docs/steps/set-pipeline.md
      load-var-step.html.md: docs/steps/load-var.md
      load-var-step.md: docs/steps/load-var.md
      in-parallel-step.html.md: docs/steps/in-parallel.md
      in-parallel-step.md: docs/steps/in-parallel.md
      do-step.html.md: docs/steps/do.md
      do-step.md: docs/steps/do.md
      try-step.html.md: docs/steps/try.md
      try-step.md: docs/steps/try.md
      modifier-and-hook-steps.html.md: docs/steps/modifier-and-hooks/index.md
      modifier-and-hook-steps.md: docs/steps/modifier-and-hooks/index.md
      across-step.html.md: docs/steps/modifier-and-hooks/across.md
      across-step.md: docs/steps/modifier-and-hooks/across.md
      timeout-step.html.md: docs/steps/modifier-and-hooks/timeout.md
      timeout-step.md: docs/steps/modifier-and-hooks/timeout.md
      attempts-step.html.md: docs/steps/modifier-and-hooks/attempts.md
      attempts-step.md: docs/steps/modifier-and-hooks/attempts.md
      tags-step.html.md: docs/steps/modifier-and-hooks/tags.md
      tags-step.md: docs/steps/modifier-and-hooks/tags.md
      on-success-step.html.md: docs/steps/modifier-and-hooks/on-success.md
      on-success-step.md: docs/steps/modifier-and-hooks/on-success.md
      on-failure-hook.html.md: docs/steps/modifier-and-hooks/on-failure.md
      on-failure-hook.md: docs/steps/modifier-and-hooks/on-failure.md
      on-abort-hook.html.md: docs/steps/modifier-and-hooks/on-abort.md
      on-abort-hook.md: docs/steps/modifier-and-hooks/on-abort.md
      on-error-hook.html.md: docs/steps/modifier-and-hooks/on-error.md
      on-error-hook.md: docs/steps/modifier-and-hooks/on-error.md
      ensure-hook.html.md: docs/steps/modifier-and-hooks/ensure.md
      ensure-hook.md: docs/steps/modifier-and-hooks/ensure.md
      how-to-guides.html.md: docs/how-to/index.md
      how-to-guides.md: docs/how-to/index.md
      pipeline-guides.html.md: docs/how-to/pipeline-guides/index.md
      pipeline-guides.md: docs/how-to/pipeline-guides/index.md
      managing-pipeline-configurations.html.md: docs/how-to/pipeline-guides/managing-pipeline-configs.md
      managing-pipeline-configurations.md: docs/how-to/pipeline-guides/managing-pipeline-configs.md
      common-pipeline-practices.html.md: docs/how-to/pipeline-guides/common-pipeline.md
      common-pipeline-practices.md: docs/how-to/pipeline-guides/common-pipeline.md
      exploring-task-input-and-output-scenarios.html.md: docs/how-to/pipeline-guides/task-inputs-outputs.md
      exploring-task-input-and-output-scenarios.md: docs/how-to/pipeline-guides/task-inputs-outputs.md
      gated-pipeline-patterns.html.md: docs/how-to/pipeline-guides/gated-pipelines.md
      gated-pipeline-patterns.md: docs/how-to/pipeline-guides/gated-pipelines.md
      time-triggered-pipeline-patterns.html.md: docs/how-to/pipeline-guides/time-triggered-pipelines.md
      time-triggered-pipeline-patterns.md: docs/how-to/pipeline-guides/time-triggered-pipelines.md
      manual-approval-step.html.md: docs/how-to/pipeline-guides/manual-approval.md
      manual-approval-step.md: docs/how-to/pipeline-guides/manual-approval.md
      git-guides.html.md: docs/how-to/git-guides/index.md
      git-guides.md: docs/how-to/git-guides/index.md
      basic-git-operations.html.md: docs/how-to/git-guides/basic.md
      basic-git-operations.md: docs/how-to/git-guides/basic.md
      multi-branch-workflows.html.md: docs/how-to/git-guides/multi-branch.md
      multi-branch-workflows.md: docs/how-to/git-guides/multi-branch.md
      container-image-guides.html.md: docs/how-to/container-image-guides/index.md
      container-image-guides.md: docs/how-to/container-image-guides/index.md
      building-and-pushing-an-image.html.md: docs/how-to/container-image-guides/build-push.md
      building-and-pushing-an-image.md: docs/how-to/container-image-guides/build-push.md
      building-an-image-and-using-it-in-a-task.html.md: docs/how-to/container-image-guides/build-use.md
      building-an-image-and-using-it-in-a-task.md: docs/how-to/container-image-guides/build-use.md
      operation.html.md: docs/operation/index.md
      operation.md: docs/operation/index.md
      metrics.html.md: docs/operation/metrics.md
      metrics.md: docs/operation/metrics.md
      tracing.html.md: docs/operation/tracing.md
      tracing.md: docs/operation/tracing.md
      encryption.html.md: docs/operation/encryption.md
      encryption.md: docs/operation/encryption.md
      creds.html.md: docs/operation/creds/index.md
      creds.md: docs/operation/creds/index.md
      vault-credential-manager.html.md: docs/operation/creds/vault.md
      vault-credential-manager.md: docs/operation/creds/vault.md
      credhub-credential-manager.html.md: docs/operation/creds/credhub.md
      credhub-credential-manager.md: docs/operation/creds/credhub.md
      aws-ssm-credential-manager.html.md: docs/operation/creds/aws-ssm.md
      aws-ssm-credential-manager.md: docs/operation/creds/aws-ssm.md
      aws-asm-credential-manager.html.md: docs/operation/creds/aws-secrets.md
      aws-asm-credential-manager.md: docs/operation/creds/aws-secrets.md
      kubernetes-credential-manager.html.md: docs/operation/creds/kubernetes.md
      kubernetes-credential-manager.md: docs/operation/creds/kubernetes.md
      conjur-credential-manager.html.md: docs/operation/creds/conjur.md
      conjur-credential-manager.md: docs/operation/creds/conjur.md
      idtoken-credential-manager.html.md: docs/operation/creds/id-token.md
      idtoken-credential-manager.md: docs/operation/creds/id-token.md
      creds-caching.html.md: docs/operation/creds/caching.md
      creds-caching.md: docs/operation/creds/caching.md
      creds-redacting.html.md: docs/operation/creds/redacting.md
      creds-redacting.md: docs/operation/creds/redacting.md
      creds-retry-logic.html.md: docs/operation/creds/retrying-failed.md
      creds-retry-logic.md: docs/operation/creds/retrying-failed.md
      security-hardening.html.md: docs/operation/security-hardening.md
      security-hardening.md: docs/operation/security-hardening.md
      container-placement.html.md: docs/operation/container-placement.md
      container-placement.md: docs/operation/container-placement.md
      opa.html.md: docs/operation/opa-integration.md
      opa.md: docs/operation/opa-integration.md
      performance-tuning.html.md: docs/operation/tuning.md
      performance-tuning.md: docs/operation/tuning.md
      global-resources.html.md: docs/operation/global-resources.md
      global-resources.md: docs/operation/global-resources.md
      administration.html.md: docs/operation/administration.md
      administration.md: docs/operation/administration.md
      internals.html.md: docs/internals/index.md
      internals.md: docs/internals/index.md
      checker.html.md: docs/internals/checker.md
      checker.md: docs/internals/checker.md
      scheduler.html.md: docs/internals/scheduler.md
      scheduler.md: docs/internals/scheduler.md
      build-tracker.html.md: docs/internals/build-tracker.md
      build-tracker.md: docs/internals/build-tracker.md
      garbage-collector.html.md: docs/internals/garbage-collector.md
      garbage-collector.md: docs/internals/garbage-collector.md
      examples.html.md: examples/index.md
      hello-world-example.html.md: examples/hello-world.md
      hello-world-example.md: examples/hello-world.md
      serial-job-example.html.md: examples/serial-job.md
      serial-job-example.md: examples/serial-job.md
      pipeline-vars-example.html.md: examples/pipeline-vars.md
      pipeline-vars-example.md: examples/pipeline-vars.md
      set-pipelines-example.html.md: examples/set-pipeline.md
      set-pipelines-example.md: examples/set-pipeline.md
      task-inputs-outputs-example.html.md: examples/inputs-outputs.md
      task-inputs-outputs-example.md: examples/inputs-outputs.md
      time-trigger-example.html.md: examples/time-triggered.md
      time-trigger-example.md: examples/time-triggered.md
      git-trigger-example.html.md: examples/git-triggered.md
      git-trigger-example.md: examples/git-triggered.md
      manual-trigger-example.html.md: examples/manually-triggered.md
      manual-trigger-example.md: examples/manually-triggered.md
      hooks-example.html.md: examples/job-and-task-hooks.md
      hooks-example.md: examples/job-and-task-hooks.md
      golang-library-example.html.md: examples/golang-lib.md
      golang-library-example.md: examples/golang-lib.md
      rails-example.html.md: examples/rails-app.md
      rails-example.md: examples/rails-app.md
      java-example.html.md: examples/java-app.md
      java-example.md: examples/java-app.md
      nodejs-example.html.md: examples/nodejs-app.md
      nodejs-example.md: examples/nodejs-app.md
      php-example.html.md: examples/php-app.md
      php-example.md: examples/php-app.md
      project.html.md: project/index.md
      ecosystem.html.md: ecosystem/index.md
      support.html.md: support/index.md
